# Generated by Django 5.2.4 on 2025-08-11 06:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='세션 ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='세션 제목')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 날짜')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='마지막 활동')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_path', models.CharField(max_length=500, verbose_name='저장 경로')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('txt', 'Text File'), ('xlsx', 'Excel File'), ('pptx', 'PowerPoint'), ('other', 'Other')], default='other', max_length=10)),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기(bytes)')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='업로드 날짜')),
                ('is_processed', models.BooleanField(default=False, verbose_name='벡터화 완료 여부')),
                ('description', models.TextField(blank=True, null=True, verbose_name='파일 설명')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '업로드된 파일',
                'verbose_name_plural': '업로드된 파일들',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('report_type', models.CharField(choices=[('report', '보고서'), ('presentation', '발표자료'), ('summary', '요약본')], max_length=15)),
                ('status', models.CharField(choices=[('generating', '생성 중'), ('completed', '생성 완료'), ('failed', '생성 실패')], default='generating', max_length=15)),
                ('output_filename', models.CharField(max_length=255, verbose_name='출력 파일명')),
                ('output_file_path', models.CharField(max_length=500, verbose_name='출력 파일 경로')),
                ('markdown_content', models.TextField(blank=True, null=True, verbose_name='마크다운 내용')),
                ('user_query', models.TextField(verbose_name='사용자 요청')),
                ('generation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 날짜')),
                ('completion_date', models.DateTimeField(blank=True, null=True, verbose_name='완료 날짜')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='파일 크기')),
                ('download_count', models.IntegerField(default=0, verbose_name='다운로드 횟수')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='chatbot.uploadedfile', verbose_name='원본 파일')),
            ],
            options={
                'verbose_name': '생성된 보고서',
                'verbose_name_plural': '생성된 보고서들',
                'ordering': ['-generation_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', '사용자'), ('assistant', 'AI 어시스턴트'), ('system', '시스템')], max_length=10)),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='전송 시간')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession')),
                ('file_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.uploadedfile', verbose_name='참조 파일')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('ko', '한국어'), ('en', 'English')], default='ko', max_length=10, verbose_name='선호 언어')),
                ('total_uploads', models.IntegerField(default=0, verbose_name='총 업로드 수')),
                ('total_reports_generated', models.IntegerField(default=0, verbose_name='총 생성 보고서 수')),
                ('total_chat_messages', models.IntegerField(default=0, verbose_name='총 채팅 메시지 수')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입 날짜')),
                ('last_login_date', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
                ('max_file_size_mb', models.IntegerField(default=50, verbose_name='최대 파일 크기(MB)')),
                ('max_files_count', models.IntegerField(default=100, verbose_name='최대 파일 개수')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
    ]
